name = "yt-feed-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
# Comma-separated list of allowed origins
ALLOWED_ORIGINS = "https://yt.msl.cloud,http://localhost:8080,http://127.0.0.1:8080"
