name = "yt-feed-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGINS = "https://yt.msl.cloud"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "68c169e1f2f94be9ac054d7c9597ecea"
